wip: add `privatek8s` AKS cluster
jenkins-infra/kubernetes-management pull request #3194
Opened 2022-11-10 16:43 UTC by lemeurherve

2022-11-17 14:25 UTC, lemeurherve commented on config/ext_private-nginx-ingress__common.yaml
> +    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-geoip2
```suggestion
```
Not sure we'll do something about this (?)

2022-11-17 14:26 UTC, lemeurherve commented on config/ext_public-nginx-ingress__common.yaml
> +    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-geoip2
```suggestion
```
Same as above

2022-11-17 14:27 UTC, lemeurherve commented on config/ext_public-nginx-ingress__common.yaml
> +    hsts-max-age: "86400"
```suggestion
    hsts-max-age: "2592000"
```
> **Strict-Transport-Security** The "max-age" directive is too small. The minimum recommended value is 2592000 (30 days).

2022-11-17 17:20 UTC, dduportal requested changes
As discussed together, we shall break down this PR

2022-11-22 19:28 UTC, lemeurherve commented
PR broke down:
- #3233
- #3235
- #3247 (in draft while setting up a dual stack network)
- infra part in a following PR

2022-12-19 17:18 UTC, lemeurherve commented
I was wondering if I could easily reuse this PR to include the remaining changes, nope ^^

<img width="577" alt="image" src="https://user-images.githubusercontent.com/91831478/208482877-3f4e44ff-cb37-4067-ad31-f19bd33b9c3d.png">

2022-12-19 17:18 UTC, closed without merging