feat(javadoc): remove arm64 selector to rebuild the nodepool with taint
jenkins-infra/kubernetes-management pull request #4120
Opened 2023-06-29 07:46 UTC by smerleCB

as per https://github.com/jenkins-infra/helpdesk/issues/3623

2023-06-29 08:02 UTC, dduportal requested changes
Can't merge as it: this change might  migrate the workload on an intel workload which might be expected?

It does not follow the steps described in https://github.com/jenkins-infra/helpdesk/issues/3623 from my understanding: you first need a second arm64 node pool

2023-06-29 08:05 UTC, smerleCB commented
> Can't merge as it: this change might migrate the workload on an intel workload which might be expected?
> 
> It does not follow the steps described in [jenkins-infra/helpdesk#3623](https://github.com/jenkins-infra/helpdesk/issues/3623) from my understanding: you first need a second arm64 node pool

this application (javadoc) can spawn on either intel or arm64, as it's the only one on the pool right now, removing the selector should allow it to spawn on the intel while we rebuild the arm64 nodepool or I am mistaking ?

2023-06-29 11:16 UTC, dduportal commented
As seen together, the issue need to be slighlty updated to express the plan we had a consensus in the 1:1 meeting (Tl;DR; new node poole arm64 with taints, update PR here to relax constraint about the nodepool name andadd the tolerations immediatly, etc.)

2023-06-29 15:45 UTC, dduportal commented on config/javadoc.yaml
> +# hard selector to force usage of arm64 node pool to save money
```suggestion
# Specify the "hard" scheduling constraints
```

2023-06-29 15:45 UTC, dduportal commented on config/javadoc.yaml
>    kubernetes.io/arch: arm64
```suggestion
  # Ensure ARM64 is used to decrease cloud bill (instead of using `amd64`
  kubernetes.io/arch: arm64
```

2023-06-30 10:58 UTC, dduportal commented
Setting it to draft (ref. https://github.com/jenkins-infra/helpdesk/issues/3623#issuecomment-1613504371) until @smerleCB @smerle33 is back from vacations

2023-07-31 13:23 UTC, dduportal approved these changes

2023-07-31 13:24 UTC, dduportal commented
- Code is 👍 and the toleration has been tested in #4206 
- Helmfile diff is 👍

2023-07-31 13:24 UTC, merged