feat: add custom header to `infra.ci.jenkins.io`
jenkins-infra/kubernetes-management pull request #4273
Opened 2023-08-21 20:10 UTC by lemeurherve

Configuring https://plugins.jenkins.io/customizable-header already present in our weekly image, similar to what's already set on weekly.ci.jenkins.io

![image](https://github.com/jenkins-infra/kubernetes-management/assets/91831478/59a48998-e0b6-403c-815a-e96fb434706a)

Note: not a fan but there is also an option to use a custom "context aware" logo, which replace the beekeeper logo by the current page icon (not activated in this PR):

<details>

<img width="387" alt="image" src="https://github.com/jenkins-infra/kubernetes-management/assets/91831478/85c39100-5b66-462a-9b7f-a0e5c8a408fc">

<img width="390" alt="image" src="https://github.com/jenkins-infra/kubernetes-management/assets/91831478/762fa5f5-7f7a-4306-b6f6-d31bdfbf8fb4">

</details>

2023-08-22 15:47 UTC, timja requested changes
What does it look like when you use dark theme?

Please provide a screenshot

2023-08-22 16:07 UTC, lemeurherve commented
@timja it doesn't look that good with dark theme indeed:
<img width="2160" alt="image" src="https://github.com/jenkins-infra/kubernetes-management/assets/91831478/9dfc3929-6e38-463c-a311-7d4f10ed70f3">

2023-08-22 16:12 UTC, lemeurherve commented
The Header text color doesn't change the title text color (set to `var(--text-color)`):

<img width="851" alt="image" src="https://github.com/jenkins-infra/kubernetes-management/assets/91831478/03556051-11ad-43d7-90d0-75ef70b0288f">

<img width="2154" alt="image" src="https://github.com/jenkins-infra/kubernetes-management/assets/91831478/4ed43de4-225e-4534-a75b-95aa8c85adc1">

<img width="254" alt="image" src="https://github.com/jenkins-infra/kubernetes-management/assets/91831478/125bcbae-d051-44a8-a072-7783b0d01f8e">

2023-08-22 16:14 UTC, lemeurherve commented
@mawinter69 is it a known issue of the plugin or should I open one?

2023-08-22 16:17 UTC, lemeurherve commented
Oh:

<img width="1088" alt="image" src="https://github.com/jenkins-infra/kubernetes-management/assets/91831478/5a38ec58-5046-42f0-a4ad-b88d63552c9d">

2023-08-22 16:19 UTC, lemeurherve commented
Found a workaround, no "Text" no text color issue ^^

<img width="685" alt="image" src="https://github.com/jenkins-infra/kubernetes-management/assets/91831478/99a7fecc-4579-48f7-8135-7f542779eb82">

Would that be OK for you @timja ?

2023-08-22 16:20 UTC, lemeurherve commented on config/jenkins_infra.ci.jenkins.io.yaml
> +            logoText: "Jenkins Infra"
```suggestion
```

2023-08-22 18:40 UTC, mawinter69 commented
This is related to https://github.com/jenkinsci/dark-theme-plugin/pull/380 which removed the logo-bg overwriting in the dark theme plugin. I opened https://github.com/jenkinsci/customizable-header-plugin/issues/13 for this

2023-08-22 19:18 UTC, mawinter69 commented
[18.v820da_cd15cb_1](https://github.com/jenkinsci/customizable-header-plugin/releases/tag/18.v820da_cd15cb_1) fixes the problem with the background color of the logo.

2023-08-22 20:22 UTC, mawinter69 commented on config/jenkins_infra.ci.jenkins.io.yaml
> +              hoverColor: "grey"
I would suggest not using grey but a color that you see on the gradient in the middle

2023-08-24 21:32 UTC, timja commented on config/jenkins_infra.ci.jenkins.io.yaml
> +              svg:
svg doesn't seem to render well in dark mode, png looks a lot better
<img width="236" alt="image" src="https://github.com/jenkins-infra/kubernetes-management/assets/21194782/bdc1d281-2b60-4840-a81a-0c3b418bcb20">

2023-08-24 21:34 UTC, timja reviewed
Looks nice imo with:

<img width="1436" alt="image" src="https://github.com/jenkins-infra/kubernetes-management/assets/21194782/2d9955be-e30a-4779-be0a-5e1fc46f07e9">

```yaml
  customHeaderConfiguration:
    enabled: true
    header: "logo"
    headerColor:
      backgroundColor: "linear-gradient(90deg, rgba(239,192,92,1) 0%, rgba(171,28,28,1)\
        \ 100%);"
      color: "white"
      hoverColor: "grey"
    logo:
      image:
        logoUrl: "https://www.jenkins.io/images/logos/beekeeper/beekeeper.png"
    logoText: "Jenkins Infra"
```

2023-09-10 12:22 UTC, lemeurherve commented
Thanks for the reviews and suggestions!

Here is what I've come with, using the png logo and changing the hover color, WDYT?

Before:
<img width="1402" alt="image" src="https://github.com/jenkins-infra/kubernetes-management/assets/91831478/169a25ed-8e89-43a2-bc12-57c235989996">

Light theme:
<img width="1415" alt="image" src="https://github.com/jenkins-infra/kubernetes-management/assets/91831478/4099083b-556d-4336-859d-f2a9deec94b8">

Dark theme:
<img width="1407" alt="image" src="https://github.com/jenkins-infra/kubernetes-management/assets/91831478/2f365be9-57e4-44b8-8df9-af3ee7fe0521">

2023-09-10 13:44 UTC, timja approved these changes

2023-09-10 17:16 UTC, merged