feat(updates.jenkins.io): add rsyncd service
jenkins-infra/kubernetes-management pull request #4278
Opened 2023-08-23 14:22 UTC by lemeurherve

Follow-up of https://github.com/jenkins-infra/helm-charts/pull/609

Ref: https://github.com/jenkins-infra/helpdesk/issues/2649

2023-08-23 14:39 UTC, dduportal requested changes
It's weird: the helmfil diff (for update-jenkins-io in publick8s) shows that the mirrorbits deployment is removed while a new deployment for rsyncd is added.

Is that expected?

2023-08-23 14:43 UTC, lemeurherve commented
Here is the result of `helmfile template -f clusters/publick8s.yaml -l name=updates-jenkins-io > uc11-add-rsyncd.yaml`:

<details>

```
---
# Source: mirrorbits/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: updates-jenkins-io
type: Opaque
data:
...
---
# Source: mirrorbits/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: updates-jenkins-io-geoipupdate
type: Opaque
data:
...
---
# Source: mirrorbits/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: updates-jenkins-io-binary
type: Opaque
data:
...
---
# Source: mirrorbits/templates/configmap.files.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: updates-jenkins-io-files
data:
  httpd.conf: |
    ServerRoot "/usr/local/apache2"
    
    Listen 80
    
    #
    # Dynamic Shared Object (DSO) Support
    #
    # To be able to use the functionality of a module which was built as a DSO you
    # have to place corresponding `LoadModule' lines at this location so the
    # directives contained in it are actually available _before_ they are used.
    # Statically compiled modules (those listed by `httpd -l') do not need
    # to be loaded here.
    #
    # Example:
    # LoadModule foo_module modules/mod_foo.so
    #
    LoadModule mpm_event_module modules/mod_mpm_event.so
    #LoadModule mpm_prefork_module modules/mod_mpm_prefork.so
    #LoadModule mpm_worker_module modules/mod_mpm_worker.so
    LoadModule authn_file_module modules/mod_authn_file.so
    #LoadModule authn_dbm_module modules/mod_authn_dbm.so
    #LoadModule authn_anon_module modules/mod_authn_anon.so
    #LoadModule authn_dbd_module modules/mod_authn_dbd.so
    #LoadModule authn_socache_module modules/mod_authn_socache.so
    LoadModule authn_core_module modules/mod_authn_core.so
    LoadModule authz_host_module modules/mod_authz_host.so
    LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
    LoadModule authz_user_module modules/mod_authz_user.so
    #LoadModule authz_dbm_module modules/mod_authz_dbm.so
    #LoadModule authz_owner_module modules/mod_authz_owner.so
    #LoadModule authz_dbd_module modules/mod_authz_dbd.so
    LoadModule authz_core_module modules/mod_authz_core.so
    #LoadModule authnz_ldap_module modules/mod_authnz_ldap.so
    #LoadModule authnz_fcgi_module modules/mod_authnz_fcgi.so
    LoadModule access_compat_module modules/mod_access_compat.so
    LoadModule auth_basic_module modules/mod_auth_basic.so
    #LoadModule auth_form_module modules/mod_auth_form.so
    #LoadModule auth_digest_module modules/mod_auth_digest.so
    #LoadModule allowmethods_module modules/mod_allowmethods.so
    #LoadModule isapi_module modules/mod_isapi.so
    #LoadModule file_cache_module modules/mod_file_cache.so
    #LoadModule cache_module modules/mod_cache.so
    #LoadModule cache_disk_module modules/mod_cache_disk.so
    #LoadModule cache_socache_module modules/mod_cache_socache.so
    #LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
    #LoadModule socache_dbm_module modules/mod_socache_dbm.so
    #LoadModule socache_memcache_module modules/mod_socache_memcache.so
    #LoadModule socache_redis_module modules/mod_socache_redis.so
    #LoadModule watchdog_module modules/mod_watchdog.so
    #LoadModule macro_module modules/mod_macro.so
    #LoadModule dbd_module modules/mod_dbd.so
    #LoadModule bucketeer_module modules/mod_bucketeer.so
    #LoadModule dumpio_module modules/mod_dumpio.so
    #LoadModule echo_module modules/mod_echo.so
    #LoadModule example_hooks_module modules/mod_example_hooks.so
    #LoadModule case_filter_module modules/mod_case_filter.so
    #LoadModule case_filter_in_module modules/mod_case_filter_in.so
    #LoadModule example_ipc_module modules/mod_example_ipc.so
    #LoadModule buffer_module modules/mod_buffer.so
    #LoadModule data_module modules/mod_data.so
    #LoadModule ratelimit_module modules/mod_ratelimit.so
    LoadModule reqtimeout_module modules/mod_reqtimeout.so
    #LoadModule ext_filter_module modules/mod_ext_filter.so
    #LoadModule request_module modules/mod_request.so
    #LoadModule include_module modules/mod_include.so
    LoadModule filter_module modules/mod_filter.so
    #LoadModule reflector_module modules/mod_reflector.so
    #LoadModule substitute_module modules/mod_substitute.so
    #LoadModule sed_module modules/mod_sed.so
    #LoadModule charset_lite_module modules/mod_charset_lite.so
    #LoadModule deflate_module modules/mod_deflate.so
    #LoadModule xml2enc_module modules/mod_xml2enc.so
    #LoadModule proxy_html_module modules/mod_proxy_html.so
    #LoadModule brotli_module modules/mod_brotli.so
    LoadModule mime_module modules/mod_mime.so
    #LoadModule ldap_module modules/mod_ldap.so
    LoadModule log_config_module modules/mod_log_config.so
    #LoadModule log_debug_module modules/mod_log_debug.so
    #LoadModule log_forensic_module modules/mod_log_forensic.so
    #LoadModule logio_module modules/mod_logio.so
    #LoadModule lua_module modules/mod_lua.so
    LoadModule env_module modules/mod_env.so
    #LoadModule mime_magic_module modules/mod_mime_magic.so
    #LoadModule cern_meta_module modules/mod_cern_meta.so
    #LoadModule expires_module modules/mod_expires.so
    LoadModule headers_module modules/mod_headers.so
    #LoadModule ident_module modules/mod_ident.so
    #LoadModule usertrack_module modules/mod_usertrack.so
    #LoadModule unique_id_module modules/mod_unique_id.so
    LoadModule setenvif_module modules/mod_setenvif.so
    LoadModule version_module modules/mod_version.so
    #LoadModule remoteip_module modules/mod_remoteip.so
    #LoadModule proxy_module modules/mod_proxy.so
    #LoadModule proxy_connect_module modules/mod_proxy_connect.so
    #LoadModule proxy_ftp_module modules/mod_proxy_ftp.so
    #LoadModule proxy_http_module modules/mod_proxy_http.so
    #LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
    #LoadModule proxy_scgi_module modules/mod_proxy_scgi.so
    #LoadModule proxy_uwsgi_module modules/mod_proxy_uwsgi.so
    #LoadModule proxy_fdpass_module modules/mod_proxy_fdpass.so
    #LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
    #LoadModule proxy_ajp_module modules/mod_proxy_ajp.so
    #LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
    #LoadModule proxy_express_module modules/mod_proxy_express.so
    #LoadModule proxy_hcheck_module modules/mod_proxy_hcheck.so
    #LoadModule session_module modules/mod_session.so
    #LoadModule session_cookie_module modules/mod_session_cookie.so
    #LoadModule session_crypto_module modules/mod_session_crypto.so
    #LoadModule session_dbd_module modules/mod_session_dbd.so
    #LoadModule slotmem_shm_module modules/mod_slotmem_shm.so
    #LoadModule slotmem_plain_module modules/mod_slotmem_plain.so
    #LoadModule ssl_module modules/mod_ssl.so
    #LoadModule optional_hook_export_module modules/mod_optional_hook_export.so
    #LoadModule optional_hook_import_module modules/mod_optional_hook_import.so
    #LoadModule optional_fn_import_module modules/mod_optional_fn_import.so
    #LoadModule optional_fn_export_module modules/mod_optional_fn_export.so
    #LoadModule dialup_module modules/mod_dialup.so
    #LoadModule http2_module modules/mod_http2.so
    #LoadModule proxy_http2_module modules/mod_proxy_http2.so
    #LoadModule md_module modules/mod_md.so
    #LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so
    #LoadModule lbmethod_bytraffic_module modules/mod_lbmethod_bytraffic.so
    #LoadModule lbmethod_bybusyness_module modules/mod_lbmethod_bybusyness.so
    #LoadModule lbmethod_heartbeat_module modules/mod_lbmethod_heartbeat.so
    LoadModule unixd_module modules/mod_unixd.so
    #LoadModule heartbeat_module modules/mod_heartbeat.so
    #LoadModule heartmonitor_module modules/mod_heartmonitor.so
    #LoadModule dav_module modules/mod_dav.so
    LoadModule status_module modules/mod_status.so
    LoadModule autoindex_module modules/mod_autoindex.so
    #L [...]

2023-08-23 14:43 UTC, lemeurherve commented
All three expected `deployment`s are present, LGTM, I'd say it's a display/report issue.

2023-08-23 16:58 UTC, lemeurherve commented
The ingress should be replaced by a load balancer like it's done for the LDAP service, as rsync is a TCP service, not a HTTP one.

2023-08-23 17:51 UTC, lemeurherve commented
Needs https://github.com/jenkins-infra/azure/pull/459

2023-08-24 08:18 UTC, dduportal commented
Fails with the following error:

```
Error: Failed to render chart: exit status 1: Error: template: mirrorbits/templates/deployment.rsyncd.yaml:47:26: executing "mirrorbits/templates/deployment.rsyncd.yaml" at <.Values.rsyncd.configurationFiles.rsyncdConf.override>: nil pointer evaluating interface {}.override
```

Taking over the PR as Hervé is in holidays and shared knowledge: currently trying locally

2023-08-24 09:47 UTC, dduportal approved these changes
https://github.com/jenkins-infra/azure/pull/459#issuecomment-1690750706 => LGTM let's go

2023-08-24 09:47 UTC, merged