feat(infra.ci.jio): Added AZ VM templates for Ubuntu-22 AMD and ARM maven-17 and maven-21 agents
jenkins-infra/kubernetes-management pull request #5526
Opened 2024-08-11 14:39 UTC by jayfranco999

As per https://github.com/jenkins-infra/helpdesk/issues/4124#issuecomment-2275506395

Added jdk-17 and jdk-21 (AMD and ARM) ssh agents to infra.ci, Ubuntu-22 (AMD and ARM) template will have jdk-11 by default.

2024-08-12 06:33 UTC, dduportal requested changes
First batch of reviews

2024-08-12 06:33 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  javaHome: "/opt/jdk-11"
```suggestion
```

Not a JCasc valid attribute :)

2024-08-12 06:33 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                    update-alternatives --install /usr/bin/java java "${DEFAULT_JDK}/bin/java" 2000
```suggestion
                    update-alternatives --install /usr/bin/java java "^${DEFAULT_JDK}/bin/java" 2000
```

Need to escape `$` sign on JCasc if you want it to be litteral

2024-08-12 06:33 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                    echo "JAVA_HOME=${DEFAULT_JDK}" >> /etc/environment
```suggestion
                    echo "JAVA_HOME=^${DEFAULT_JDK}" >> /etc/environment
```

Need to escape `$` sign on JCasc if you want it to be litteral

2024-08-12 06:33 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  templateDesc: "Dynamically provisioned Ubuntu 22.04 LTS AMD machine"
```suggestion
                  templateDesc: "Dynamically provisioned Ubuntu 22.04 LTS x86_64 machine"
```

2024-08-12 06:33 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                    echo "JAVA_HOME=${DEFAULT_JDK}" >> /etc/environment
```suggestion
                    update-alternatives --install /usr/bin/java java "^${DEFAULT_JDK}/bin/java" 2000
                    echo "JAVA_HOME=^${DEFAULT_JDK}" >> /etc/environment
```

2024-08-12 06:33 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  javaHome: "/opt/jdk-17"
```suggestion
```

2024-08-12 06:33 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  templateDesc: "Dynamically provisioned Ubuntu 22.04 maven-17 LTS AMD machine"
```suggestion
                  templateDesc: "Dynamically provisioned Ubuntu 22.04 maven-17 LTS x86_64 machine"
```

2024-08-12 06:33 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                    echo "JAVA_HOME=${DEFAULT_JDK}" >> /etc/environment
```suggestion
                    update-alternatives --install /usr/bin/java java "^${DEFAULT_JDK}/bin/java" 2000
                    echo "JAVA_HOME=^${DEFAULT_JDK}" >> /etc/environment
```

2024-08-12 06:33 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  javaHome: "/opt/jdk-21"
```suggestion
```

2024-08-12 06:33 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  templateDesc: "Dynamically provisioned Ubuntu 22.04 maven-21 LTS AMD machine"
```suggestion
                  templateDesc: "Dynamically provisioned Ubuntu 22.04 maven-21 LTS x86_64 machine"
```

2024-08-12 06:33 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                    echo "JAVA_HOME=${DEFAULT_JDK}" >> /etc/environment
```suggestion
                    update-alternatives --install /usr/bin/java java "^${DEFAULT_JDK}/bin/java" 2000
                    echo "JAVA_HOME=^${DEFAULT_JDK}" >> /etc/environment
```

2024-08-12 06:33 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  javaHome: "/opt/jdk-11"
```suggestion
```

2024-08-12 06:33 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  labels: "linux-arm64 linux-arm64-docker azure-vms-jenkins-sponsorship arm64linux jdk11 maven-11"
Is it the default to use? Or the amd64? ;)

2024-08-12 10:08 UTC, jayfranco999 commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                    update-alternatives --install /usr/bin/java java "${DEFAULT_JDK}/bin/java" 2000
```suggestion
                    update-alternatives --install /usr/bin/java java "^${DEFAULT_JDK}/bin/java" 2000
```

2024-08-12 10:10 UTC, jayfranco999 commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  labels: "linux-arm64 linux-arm64-docker azure-vms-jenkins-sponsorship arm64linux jdk11 maven-11"
```suggestion
                  labels: "linux-arm64 linux-arm64-docker azure-vms-jenkins-sponsorship arm64linux jdk11-arm64 maven-11-arm-64"
```

2024-08-12 10:11 UTC, jayfranco999 commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                    update-alternatives --install /usr/bin/java java "${DEFAULT_JDK}/bin/java" 2000
```suggestion
                    update-alternatives --install /usr/bin/java java "^${DEFAULT_JDK}/bin/java" 2000
```

2024-08-12 10:12 UTC, jayfranco999 commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  javaHome: "/opt/jdk-17"
```suggestion
```

2024-08-12 12:39 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                    gallerySubscriptionId: "^${JENKINSINFRA_AZURE_SECONDARY_SUBSCRIPTION_ID}"
What is the reason of this change @jayfranco999 ? it is unrelated to your PR and will break things 🤔

2024-08-14 05:06 UTC, jayfranco999 commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                    gallerySubscriptionId: "^${JENKINSINFRA_AZURE_SECONDARY_SUBSCRIPTION_ID}"
```suggestion
                    gallerySubscriptionId: "${JENKINSINFRA_AZURE_SECONDARY_SUBSCRIPTION_ID}"
```

2024-08-14 05:06 UTC, jayfranco999 commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                    sed 's/api_key:.*/api_key: ^${JENKINS_CI_DATADOG_API_KEY}/' /etc/datadog-agent/datadog.yaml.example > /etc/datadog-agent/datadog.yaml
```suggestion
                    sed 's/api_key:.*/api_key: ${JENKINS_CI_DATADOG_API_KEY}/' /etc/datadog-agent/datadog.yaml.example > /etc/datadog-agent/datadog.yaml
```

2024-08-14 05:07 UTC, jayfranco999 commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  existingStorageAccountName: "^${AZURE_VM_AGENTS_STORAGE_ACCOUNT_SECONDARY_SUBSCRIPTION}"
```suggestion
                  existingStorageAccountName: "${AZURE_VM_AGENTS_STORAGE_ACCOUNT_SECONDARY_SUBSCRIPTION}"
```

2024-08-14 11:40 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  labels: "linux-amd64 linux-amd64-docker azure-vms-jenkins-sponsorship jdk11 maven-11"
```suggestion
                  labels: "linux-amd64 linux-amd64-docker azure-vms-jenkins-sponsorship"
```

We discussed about using the ARM64 as default in this controller (we like to live on the edge ;) )

2024-08-14 11:44 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  labels: "linux-arm64 linux-arm64-docker azure-vms-jenkins-sponsorship arm64linux jdk11-arm64 maven-11-arm64"
```suggestion
                  labels: "linux-arm64 linux-arm64-docker azure-vms-jenkins-sponsorship arm64linux jdk11 maven-11 ubuntu-22-arm64 ubuntu-arm64"
```

- Add the default JDK11 labels for existing pipelines (ref. https://github.com/jenkins-infra/kubernetes-management/pull/5526/files#r1716774585)
- Add the templateName as explicit label
- Add an ubuntu "non-versioned" default label

2024-08-14 11:45 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  virtualNetworkResourceGroupName: "infra-ci-jenkins-io-sponsorship"
```suggestion
```

Let's try to use only arm64, and we keep 1 x86_64 for backward compatibility

2024-08-14 11:48 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  labels: "linux-arm64-maven-17"
```suggestion
                  labels: "linux-arm64-maven-17 jdk17 maven-17 ubuntu-22-arm64-maven-17 ubuntu-arm64-maven-17"
```

2024-08-14 11:48 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                  labels: "linux-arm64-maven-21"
```suggestion
                  labels: "linux-arm64-maven-21 jdk21 maven-21 ubuntu-22-arm64-maven-21 ubuntu-arm64-maven-21"
```

2024-08-14 12:03 UTC, dduportal approved these changes
LGTM! Helm file diff looks good!

2024-08-14 12:03 UTC, merged