fix(infra.ci.jio): init script test for ssh AZ agents
jenkins-infra/kubernetes-management pull request #5584
Opened 2024-08-20 05:25 UTC by jayfranco999

As per https://github.com/jenkins-infra/helpdesk/issues/4244#issue-2472582870 :

init script of Linux SSH AZ agents in infra.ci is now in sync with the puppet code. If it tests successful we can proceed with the agent builds https://github.com/jenkins-infra/helpdesk/issues/4124#issuecomment-2295792812

2024-08-20 07:52 UTC, timja approved these changes

2024-08-20 07:52 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                      sed 's/api_key:.*/api_key: ^${JENKINS_CI_DATADOG_API_KEY}/' /etc/datadog-agent/datadog.yaml.example > /etc/datadog-agent/datadog.yaml
```suggestion
                      sed 's/api_key:.*/api_key: ${JENKINS_CI_DATADOG_API_KEY}/' /etc/datadog-agent/datadog.yaml.example > /etc/datadog-agent/datadog.yaml
```

The API key is secret value: it's passed to JCasc through a Kubernets Secret, so we want it to be set by JCasc.
As such, no escaping: it MUST be using the interpolation syntax.

Another way to look at it is the following: it was already using the "non escaped" version and was working so there is no reason to change it.

2024-08-20 07:54 UTC, dduportal commented on config/jenkins_infra.ci.jenkins.io.yaml
> +                      systemctl daemon-reload
Note: I believe this line is the real "root cause" fix and explains why datadog agent was starting flawlessly on ci.jenkins.io but was failing on infra.ci.

2024-08-20 07:55 UTC, dduportal requested changes
LGTM! Only one element to fix before merging this (see suggestion).

Good job!

2024-08-20 13:09 UTC, timja approved these changes

2024-08-21 07:34 UTC, dduportal approved these changes

2024-08-21 07:34 UTC, merged