feat(updatecli): Switch Helm Chart related manifest targets to native(YAML) queries
jenkins-infra/kubernetes-management pull request #5666
Opened 2024-09-05 16:45 UTC by jayfranco999

As per https://github.com/jenkins-infra/kubernetes-management/issues/5663#issue-2506884201:

We updated all manifest tracking Helm Charts versions to use YAML path targets instead of file targets.

It allows using YAML path queries to perform selection of the list object based on attribute filters which was the proposed solution.

2024-09-05 16:45 UTC, jayfranco999 commented
Files not updated:

updatecli/updatecli.d/charts/httpd.yaml
updatecli/updatecli.d/charts/jenkins-agents-infra.ci.jenkins.io.yaml
updatecli/updatecli.d/charts/jenkins-infra-tools-maven.yaml

2024-09-06 11:02 UTC, dduportal commented on updatecli/updatecli.d/charts/accountapp.yaml
> -    scmid: default
Sounds like a mistake: you should not remove this instructions. Otherwise the target would never be applied to the git repository

2024-09-06 11:18 UTC, dduportal commented on updatecli/updatecli.d/charts/accountapp.yaml
> -    scmid: default
👍

2024-09-06 12:22 UTC, dduportal requested changes
As see together: there a changes missing (`kind`)  otherwise it won't work as expected

2024-09-06 12:40 UTC, jayfranco999 commented
`kind: yaml` has been fixed for all the Helm Chart related manifests.

2024-09-07 09:16 UTC, merged